[package]
name = "autocommit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
colored = "2.0.0"
derive_builder = "0.12.0"
dirs = "5.0.0"
futures = "0.3.28"
regex = "1.8.1"
serde = { version = "1.0.160", features = ["derive"] }
structopt = "0.3.26"
tokio = { version = "1.27.0", features = ["full"] }
toml = "0.7.3"
